name: Wes Baker
description: RPGs, Board Games, Miniatures, Software Engineering, and Disney
meta_description: "Wes Baker: RPGs, Board Games, Miniatures, Software Engineering, and Disney"

markdown: kramdown
highlighter: rouge
logo: true
paginate: 10
baseurl: /
domain_name: 'http://wesbaker.com'
google_analytics: 'UA-89594185-1'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://wesbaker.com'
author:         'Wes Baker'
