name: Wes Baker
description: Software Engineering, Board Games, and Books
meta_description: "Wes Baker: Software Engineering, Board Games, and Books"

markdown: kramdown
highlighter: rouge
logo: true
paginate: 10
baseurl: /
domain_name: 'http://wesbaker.com'
google_analytics: 'UA-89594185-1'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://wesbaker.com'
author:         'Wes Baker'
